### ISSUE TITLE
Element wise square root for complex data types

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#314]
Currently element wise sqrt can be computed only for non-complex data types.

Having a specialized function for complex, with the same interface (`#sqrt`) would be great.

**Comment by mohawkjohn** [comment]
There is no `Complex#sqrt`. How is the square root of -_i_ defined, for example?

**Comment by v0dro** [comment]
Heres a resouce : http://math.stackexchange.com/questions/44406/how-do-i-get-the-square-root-of-a-complex-number

**Comment by mohawkjohn** [comment]
And the very first answer says it's not well-defined.

**Comment by v0dro** [comment]
There are ways to compute it. It turns out to be another complex number.

Subsequent answers in that link elaborate on that, plus I found another resource [here](http://mathworld.wolfram.com/SquareRoot.html) which is also interesting.

**Comment by mohawkjohn** [comment]
The problem is that there are two roots (a positive and a negative complex number) for each complex number. Most of the math functions yield a single number, and square root is expected to yield a single number. You'd have to redefine the operator if you wanted to use it on complex, and I think that's not something we should do without a particularly compelling reason.

**Comment by v0dro** [comment]
By that logic all numbers can have two square roots (positive and negative), we can just change the implementation such that only the positive complex number is returned, keeping the interface consistent.

**Comment by mohawkjohn** [comment]
That's arbitrary and not a good way to write a library. Again, I think the more common use-cases support people writing their own complex square root implementations.
