### ISSUE TITLE
An easier way to create template tables with specific dtypes

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#318]
To access a templated C++ function it first necessary to create a function pointer table using something  `NAMED_DTYPE_TEMPLATE_TABLE(....)`.

This is fine if your C++ functions works fine for all NMatrix data types, but gets awkward when it works only for certain data types (say just `float32` and `float64`); which leads to the writing of something like this:

``` C++

    static void (*ttable[nm::NUM_DTYPES])(const int, void*) = {
        NULL, NULL, NULL, NULL, NULL, // does not support ints
        nm::math::hessenberg<float>,
        nm::math::hessenberg<double>,
        NULL, NULL, // does not support Complex
        NULL,NULL, NULL, // no support for rationals
        NULL // no support for Ruby Object
    };
```
... if your function works only for floating  point data types.

What would be great would be something like `CUSTOM_TEMPLATE_TABLE(float32, float64)` for only floating points or maybe `CUSTOM_TEMPLATE_TABLE(float32, float64, complex32, complex64, complex128)` for both float and complex.

I'm purely speculating about the actual implementation but you get the idea.

**Comment by cjfuller** [comment]
I'm not sure what the best answer is here.

One thing I don't like about this approach is that it's kind of difficult to include dtype checking (though maybe someone with more C preprocessor macro wizardry than I have could figure out how).  So, if someone just naively only uses the custom template macro, and then calls the method on NMatrix with the wrong dtype, what happens?  Probably a segfault since the function pointers are all null?  To prevent that from happening, we'd need to either add rb_raise in the C code for each dtype, or dtype checks in the ruby code, but then we have to have the list of supported dtypes in two places, which makes maintenance harder.

Off the top of my head, I think I'd prefer the approach of making all functions templated for all dtypes, and then just raising (either in the C code or ruby) on unsupported dtypes.  However, this approach bloats the executable (probably not so bad, especially for functions that only depend on one matrix?), and it also leaves us without a unified approach to specifying limited dtype support.  So, not sure this is the answer either.

More generally, my feeling is that, especially if we're pondering support for different backends, or making compilation with atlas optional (and thus end up with even more versions of each function, or conditional inclusion of each function), we're going to need to improve the templating system generally if we want to keep things manageable.  Perhaps this would be best considered as one part of an improved system rather than its own piece?

Further discussion encouraged!  In my experience, understanding the template system is a major barrier to entry for hacking on NMatrix code, so ideas here are always welcome.  I just want to guard against making it more complex than it already is.

**Comment by cjfuller** [comment]
Actually now that I think about it, maybe error handling isn't that big a deal; we could just make the function pointer point to a function that always raises an error about the dtypes.

I still think in general, though, we should think about how we might want some future extensible C <=> C++ templating system to look before adding convenience macros to the current system.

**Comment by v0dro** [comment]
I was reading [numpy's implementation of data types](http://docs.scipy.org/doc/numpy/reference/c-api.types-and-structures.html#c.PyArray_Type), and they use C `structs` for abstracting data types from Python.

To pass the data into a LAPACK function, its just serialized into an array of a specific type and passed into the function. Also, they've used code generators to generate C functions for supporting multiple data types, no C++ at all.

Can we use something similar? This is interesting because I'm thinking of proposing a plug-in system for nmatrix for my GSOC project and a major concern is how extensions to nmatrix can efficiently handle data [without having to call ruby methods from C code](http://docs.scipy.org/doc/numpy/reference/c-api.types-and-structures.html#c.PyArray_Type).

**Comment by mohawkjohn** [comment]
We actually used to use something similar — all of NMatrix used to be
written in C using templates which we specialized using Ruby scripts. It
was incredibly difficult to maintain and terribly fragile.

What it sounds like you're looking for is the ability to use custom types
that are written in C. You can do this! You just have to write yourself
some Ruby classes written in C, and then use the `:object` dtype.

There's no compelling reason to add a dtype unless you need *really* fast
math — and I can't think why that would be the case for non-numeric data.
