### ISSUE TITLE
narray vs nmatrix?

### ISSUE THREAD

**Issue by minad** [SciRuby/nmatrix#375]
Both libraries seem to be maintained. Why are these projects separate? Many new libraries still rely on narray, e.g. ruby-netcdf

**Comment by mohawkjohn** [comment]
It appeared that NArray was not being maintained (there were rumors of a rewrite, but no news for a long time), so I went ahead with building NMatrix.

**Comment by agarie** [comment]
Merging NMatrix and NArray would be no trivial matter, but it "sounds" really cool. What do you think, @masa16? :)

**Comment by v0dro** [comment]
Close this? NMatrix now matches or outperforms NArray in almost every way. We have a very extensible architecture, interface with various libraries, and the problem of working when narray was present has also been resolved.

**Comment by kojix2** [comment]
Several years have passed since the new version of NArray came out.

It appeared that NMatrix was not being maintained well. 
And I think Numo::NArray now outperforms NMatrix in almost every way. (benchmark needed)

Newcomers try NMatrix first. After a while, they notice that NArray is far better in performance. 
And they begin to make libraries dependent on NArray.

For example,

NArray has at leaset 2 deep learning libraries. NMatrix not. 
* Red Chainer
* ruby-dnn

CUDA support. NMatrix not.
* cumo

Best machine Learning in Ruby. 
* SVMKit

I admit that I am using NArray for many years and it is far from a neutral position.
I know that this topic is controversial, but in my honest opinion, NArray become the standard again.
