### ISSUE TITLE
Document every function/macro in the C API

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#421]
I've created a file for doing this on my new branch here - https://github.com/v0dro/nmatrix/blob/nmatrix-fftw/C_API.md

Suggestions welcome.

**Comment by mohawkjohn** [comment]
Link doesn't work for me, even when I add a dot between github and com.

**Comment by v0dro** [comment]
That's strange. It's working for me.

I'm putting it up again: https://github.com/v0dro/nmatrix/blob/nmatrix-fftw/C_API.md

**Comment by mohawkjohn** [comment]
Okay, I think I misunderstood what this issue is. You want to document them all in the wiki? This is what rdoc is for. Have you tried running the appropriate rake task for generating rdocs?

**Comment by v0dro** [comment]
No not in the wiki. I want to create a file similar to README or CONTRIBUTING within the source code itself that will document the C API.

You think it should be done in the wiki? It'll separate the code from the docs then.

**Comment by mohawkjohn** [comment]
...no. Seriously, please go run rdoc on the sources and see what gets produced before you do anything else.

**Comment by v0dro** [comment]
I just did, and it turns out that RDoc does not generate anything for code present in the `nmatrix.h` file (where the C API resides), which is why I'm suggesting that we have a separate file where these macros and functions will be documented. 

Or maybe make comments in nmatrix.h itself?

**Comment by mohawkjohn** [comment]
Yeah, there's no reason not to include rdoc markup in nmatrix.h. I'm not sure why it's never been done. Actually, we could stand to improve all of our rdoc documentation quite a bit.

**Comment by wlevine** [comment]
There's a lot of documentation in ruby_nmatrix.c rather than nmatrix.h. Not all of it is collected by rdoc, because not all of the functions are directly exposed to Ruby. In general, there are some issues with using RDoc with C extensions, especially when things are spread out across multiple files ([details here](http://clalance.blogspot.com/2011/01/writing-ruby-extensions-in-c-part-2.html)). I ran into this problem over the summer, but I don't remember if it applied to the main nmatrix gem or not. It's clear that [rdoc is picking up at least some (most?) of our Ruby methods implemented in C](http://sciruby.com/nmatrix/docs/NMatrix.html).
