### ISSUE TITLE
cblas_trsm behaves differently with/without lapacke plugin

### ISSUE THREAD

**Issue by agisga** [SciRuby/nmatrix#422]
When solving a lower triangular linear system with `cblas_trsm`, I get different results depending on whether I require `nmatrix-lapacke` (or `nmatrix-atlas`) or not. With the lapacke or atlas plugins I get the correct result, but without the plugins the method returns a wrong solution.

Example: The following script

```Ruby
require 'nmatrix'

a = NMatrix.new([3,3], [1, 0, 0, 2, 0.5, 0, 3, 3, 9], dtype: :float64)
b = NMatrix.new([3,1], [1,2,3], dtype: :float64)
x = b.clone
NMatrix::BLAS::cblas_trsm(:row, :left, :lower, false, :nounit, x.shape[0], 
                          x.shape[1], 1.0, a, a.shape[0], x, x.shape[1])
puts "without plugin: #{x}"

require 'nmatrix/lapacke'
a = NMatrix.new([3,3], [1, 0, 0, 2, 0.5, 0, 3, 3, 9], dtype: :float64)
b = NMatrix.new([3,1], [1,2,3], dtype: :float64)
x = b.clone
NMatrix::BLAS::cblas_trsm(:row, :left, :lower, false, :nounit, x.shape[0], 
                          x.shape[1], 1.0, a, a.shape[0], x, x.shape[1])
puts "with plugin: #{x}"
```

produces

```
without plugin: [1.0, 4.0, 0.0]
with plugin: [1.0, 0.0, 0.0]
```

The solution obtained with `nmatrix-lapacke` is the correct one (`nmatrix-atlas` gives the same correct solution).

Does anybody have an idea what might be the problem?

**Comment by wlevine** [comment]
It looks like the spec only tests this with the `:right` option, while you use `:left`. That could be the source of the problem. I'm going to be super busy for the next few weeks, so I probably won't have a chance to look into this for a while.

**Comment by agisga** [comment]
You are right, this workaround produces the correct result:

```Ruby
a = a.transpose
x = b.clone.transpose
NMatrix::BLAS::cblas_trsm(:row, :right, :upper, false, :nounit, x.shape[0], 
                          x.shape[1], 1.0, a, a.shape[0], x, x.shape[1])
``` 

Also, I noticed that `cblas_trsm` seems to work flawlessly with the argument `:upper`, for upper triangular linear systems (even with option `:left`). So, the problem might also be related to the option `:lower`.

**Comment by lokeshh** [comment]
In which file is the method `cblas_trsm` defined?

**Comment by agisga** [comment]
@lokeshh As far as I can see it right now, `cblas_trsm` is defined in [`ext/nmatrix/math.cpp` line 467](https://github.com/SciRuby/nmatrix/blob/73efdf976efc9761d3818c3a3df53352c00f9395/ext/nmatrix/math.cpp#L467). However, the actual C implementation is in [`ext/nmatrix/math/trsm.h`](https://github.com/SciRuby/nmatrix/blob/master/ext/nmatrix/math/trsm.h#L275).

nmatrix-lapacke and nmatrix-atlas must be overwriting the method with an available external implementation somewhere (not sure how and where), which works fine.

**Comment by lokeshh** [comment]
I am playing with this for a while and it seems like `side == CblasLeft` always return false.

**Comment by lokeshh** [comment]
@agisga Could you give some clarification on why you passed third last and last argument as `a.shape[0]` and `x.shape[1]` respectively?

According to the [documentation](http://www.math.utah.edu/software/lapack/lapack-blas/dtrsm.html), these arguments should be number of rows of `a` and `x` respectively.

**Comment by agisga** [comment]
> So, I thought about passing number of columns of a and x respectively and it worked. Both the methods (with/without plugin) gives the same correct result if they are passed number of columns of a and x respectively.

@lokeshh Sorry, I don't have a system to try it out at this moment, but I don't see how what you are saying would give a different result than my example, because `a` has the same number of columns as rows (that's also why I passed `a.shape[0]` instead of `a.shape[1]`).
Can you please copy the exact function call here?

**Comment by lokeshh** [comment]
@agisga I am sorry, what I said above is wrong. I have to take another look.

**Comment by lokeshh** [comment]
Funny as it my seem but changing the limits going against the [fortran implementation of trsm](http://www.netlib.org/lapack/explore-html/de/da7/dtrsm_8f_source.html), fixes the bug but I don't really understand why is it so. 

I found the same thing done [over here](https://github.com/SciRuby/nmatrix/blob/702900702c70973866973d294e186e37c76b264a/ext/nmatrix/math/trsm.h#L143).

**Comment by mohawkjohn** [comment]
@lokeshh Could it because Fortran starts at 1 with its arrays and C starts at 0? I couldn't figure out exactly which lines in the Fortran implementation corresponded to the ones you changed.

**Comment by lokeshh** [comment]
@mohawkjohn [This line](https://github.com/SciRuby/nmatrix/blob/702900702c70973866973d294e186e37c76b264a/ext/nmatrix/math/trsm.h#L143) corresponds to line 319 in [Fortran implementaion] (http://www.netlib.org/lapack/explore-html/de/da7/dtrsm_8f_source.html). The changes which I have made is parallel as to what's done here. Let me explain what I have done using these lines.

If a loop in Fortran starts from `1` to `j`, then in C the corresponding loop will be from `0` to `j-1`. This is what I have seen in the translation pattern. But in the case of lines I just mentioned above, the Fortran loop runs from `1` to `i-1`, so in C equivalent the translation pattern suggests that loop should run from `0` to `i-2` but if we do this then we will have a lot of bugs. In our C implementation we have run the loop from `0` to `i-1` as can be seen [here](https://github.com/SciRuby/nmatrix/blob/702900702c70973866973d294e186e37c76b264a/ext/nmatrix/math/trsm.h#L143). I followed this same strategy and changed the limits of some loops like done with this line and now the code is bug free. 

But I don't understand why following Fortran implementation is leading to wrong result. Perhaps it's some maths involved with converting row major operations to column major equivalent. [This function](https://github.com/SciRuby/nmatrix/blob/702900702c70973866973d294e186e37c76b264a/ext/nmatrix/math/trsm.h#L275) is responsible for dealing with converting row major order operations into their equivalent column ones. Any idea where I might find documentation of this function. This doesn't seem to exist in Fortran code as it entirely supports column major operations only.

**Comment by mohawkjohn** [comment]
Sorry, you're totally right about the limits. In that case, I suspect it's because the limits aren't right for lines 140–141, not (just) because they're wrong for line 143.

I'm not really a Fortran coder, but it seems to me that the lines

    DO 160 j = 1,n
        DO 150 i = 1,m

should be iterate from 1 to n, inclusively; and iterate from 1 to m, inclusively. In C, we have iterate from 0 to n-1, inclusively; and iterate from 0 to m-1, inclusively.

Could n and m be set wrong when the function is called, possibly?

Can you do a little bit of research to find out where this algorithm comes from? I'd suggest looking at Numerical Recipes and also Matrix Computations by Golub.

The function that converts between row and column-major format is likely borrowed from ATLAS. That's where I remember getting it, anyway. And ATLAS may have a C/C++ version of the dtrsm code also, which you can use to check the limits.

**Comment by lokeshh** [comment]
I did a little research and the fault seem to lie in how we are computing the address of an element given it's row and column in the Matrix. 

Take this code for instance:

```ruby
        for (int j = 0; j < n; ++j) {
          for (int i = 0; i < m; ++i) {
            DType temp = alpha * b[i + j * ldb];
            for (int k = 0; k < i-1; ++k) { 
              temp -= a[k + i * lda] * b[k + j * ldb];
```

Here's it's Fortran equivalent:

```fortran
        DO 130 j = 1,n
          DO 120 i = 1,m
            temp = alpha*b(i,j)
              DO 110 k = 1,i - 1
                temp = temp - a(k,i)*b(k,j)
```

`a(k,i)` is translated to `a[k + i * lda]` and limits are shifted by 1 which is not correct. To see this, lets look at the element of `a` which will be accessed in the last iteration of Fortran code. The last element will be `a(m-1, m)`. Now since we have shifted the limits in our C code by 1, the last element to be accessed should be `a(m-2, m-1)`. But this is not the case, rather the last element accessed in our C code will be `a(m-3, m-1)`. This is the reason why pushing the the limit from `i-1` to `i` solves the problem.

Here's one way to solve the problem:

```ruby
        b -= 1 + ldb;
        a -= 1 + lda;
        for (int j = 1; j <= n; ++j) {
          for (int i = 1; i <= m; ++i) {
            DType temp = alpha * b[i + j * ldb];
            for (int k = 1; k <= i-1; ++k) { 
              temp -= a[k + i * lda] * b[k + j * ldb];
```

What I have done above is that I have retain the limits from the Fortran code and just applied an offset so that we get the correct element. I did this [here](https://github.com/SciRuby/nmatrix/issues/428) and it's giving the right answers now.
