### ISSUE TITLE
(Possibly?) Cannot link to nmatrix shared object in C extensions

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#475]
I'm currently trying to make [rb-gsl compatible with nmatrix](https://github.com/v0dro/rb-gsl/tree/nmatrix_compatibility) and while linking with `nmatrix.so` [seems to work](https://github.com/v0dro/rb-gsl/blob/nmatrix_compatibility/ext/gsl_native/extconf.rb#L78) during compilation, I got a whole bunch of `symbol missing` errors when I tried to access one of the variables declared in [`ruby_constants.h`](https://github.com/SciRuby/nmatrix/blob/master/ext/nmatrix/ruby_constants.h) in rb-gsl.

It other words, I think the nmatrix shared object wasn't linked with the rb-gsl binary at all. I am using a work around by redefining the [NMatrix class in rb-gsl C code itself](https://github.com/v0dro/rb-gsl/blob/nmatrix_compatibility/ext/gsl_native/gsl_nmatrix.c#L213), which gives a handle to the current NMatrix loaded in memory with `require 'nmatrix/nmatrix'`.

Might it be that something is wrong in the way we're passing the `-l` flag to GCC in the [rb-gsl `extconf.rb`](https://github.com/v0dro/rb-gsl/blob/nmatrix_compatibility/ext/gsl_native/extconf.rb#L78) or is it that the nmatrix shared object isn't getting placed in the right place in the file system?

I am using the latest NMatrix pulled from SciRuby/master, whose [`nmatrix.h` includes `ruby_constants.h`](https://github.com/SciRuby/nmatrix/blob/master/ext/nmatrix/nmatrix.h#L36).

**Comment by wlevine** [comment]
You don't actually want nmatrix.so to be explicitly linked by your rb-gsl so. This is because nmatrix.so isn't in a standard location so if your library tries to just blindly load it, it will fail. What you need is to `require nmatrix/nmatrix` (which will dynamically load nmatrix.so) before requiring your other so. Then your library should be able to find all the symbols from nmatrix.so, even though it doesn't explicitly list it as a requirement.

PS: Are you committing changes without making pull requests? This is nearly invisible to us as it doesn't generate notifications.

**Comment by v0dro** [comment]
Just some docs fixes to nmatrix C API. Alright I'll try that out and let you know.

**Comment by v0dro** [comment]
Your fix works thank you.

**Comment by mohawkjohn** [comment]
Hey @v0dro, please don't make commits without pull requests — even doc changes.

**Comment by v0dro** [comment]
Alright
