### ISSUE TITLE
Error when using with windows 8

### ISSUE THREAD

**Issue by thrabbit** [SciRuby/nmatrix#497]
Following a thread on here: http://stackoverflow.com/questions/36389449/install-error-for-nmatrix-gem-in-windows-8?noredirect=1#comment60582106_36389449

I am using windows8, ruby 2.1, rails 4.1.7

I have tried two ways to use the gem since apparently the usual  "gem install nmatrix" doesn't currently works for windows.

METHOD ONE: clone from git, cd in to folder and rake install.
then add this to gem file:
gem 'nmatrix', :path => "C:/dev/nmatrix"   ##(path to nmatrix gem folder)

The gem builds fine but I am getting the following error when runnning my app:

```
C:/Ruby21/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/depend
encies.rb:247:in `require': 126: The specified module could not be found.   - C:
/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/extensions/x86-mingw32/2.1.0/nmatrix-92
da6e583808/nmatrix.so (LoadError)
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_s
upport/dependencies.rb:247:in `block in require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_s
upport/dependencies.rb:232:in `load_dependency'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_s
upport/dependencies.rb:247:in `require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/nmatrix-92da6e583808/lib
/nmatrix/nmatrix.rb:38:in `<top (required)>'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_s
upport/dependencies.rb:247:in `require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_s
upport/dependencies.rb:247:in `block in require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_s
upport/dependencies.rb:232:in `load_dependency'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_s
upport/dependencies.rb:247:in `require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/nmatrix-92da6e583808/lib
/nmatrix.rb:28:in `<top (required)>'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runti
me.rb:76:in `require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runti
me.rb:76:in `block (2 levels) in require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runti
me.rb:72:in `each'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runti
me.rb:72:in `block in require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runti
me.rb:61:in `each'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runti
me.rb:61:in `require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler.rb:13
4:in `require'
        from C:/dev/brandprotect/config/application.rb:7:in `<top (required)>'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/command
s/runner.rb:51:in `require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/command
s/runner.rb:51:in `<top (required)>'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/command
s/commands_tasks.rb:128:in `require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/command
s/commands_tasks.rb:128:in `require_command!'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/command
s/commands_tasks.rb:95:in `runner'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/command
s/commands_tasks.rb:40:in `run_command!'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/command
s.rb:17:in `<top (required)>'
```

METHOD TWO:

add this to the gem file: gem "nmatrix", :git => "https://github.com/SciRuby/nmatrix.git"

Again The gem builds fine but I am getting the same error as in METHOD ONE when runnning my app

Any ideas how to fix this? thanks

**Comment by mohawkjohn** [comment]
@preetpalS Have you seen this error at all? I don't have access to a Windows installation.

**Comment by preetpalS** [comment]
@mohawkjohn I have seen the error before, I believe it has to do with the fact that this gem does not statically link with some library (on Windows, some Ruby installations (like the one from rubyinstaller.org when using its devkit) only temporarily modify the path of the user during the build of the gem (so some dependencies may only be available at build time); this is arguably better since this will override any compilers you may already have on your path and since it avoids polluting your path).

@thrabbit try adding your devkit vars to your path prior to running Rails using the nmatrix gem installed from the master branch off this repo at commit c48a3a1c5cc3eb3ab4f03dcba4cc0fc7eede5f5a. See the command prompt session below for how to get the gem to work on Windows (I believe there's also a way to lock a gem at a commit from a Git repo in your Gemfile as well).

@mohawkjohn See my command prompt session below as it illustrates why I came to my conclusion (I know its kind of long, but its only the way I can think of showing why I came to my conclusion):

`C:\Users\am\temp>git clone https://github.com/SciRuby/nmatrix.git
Cloning into 'nmatrix'...
remote: Counting objects: 12206, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 12206 (delta 2), reused 1 (delta 1), pack-reused 12193
Receiving objects: 100% (12206/12206), 7.55 MiB | 1.69 MiB/s, done.
Resolving deltas: 100% (6728/6728), done.
Checking connectivity... done.

C:\Users\am\temp>cd nmatrix

C:\Users\am\temp\nmatrix>ls
CONTRIBUTING.md  LICENSE.txt   Rakefile  nmatrix-atlas.gemspec    nmatrix.gemspec  travis.sh
Gemfile          Manifest.txt  ext       nmatrix-fftw.gemspec     scripts
History.txt      README.rdoc   lib       nmatrix-lapacke.gemspec  spec

C:\Users\am\temp\nmatrix>gem build nmatrix.gemspec
WARNING:  WARNING: license value 'BSD 3-clause' is invalid.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: nmatrix
  Version: 0.2.1
  File: nmatrix-0.2.1.gem

C:\Users\am\temp\nmatrix>gem install --local nmatrix-0.2.1.gem
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
***********************************************************
Welcome to SciRuby: Tools for Scientific Computing in Ruby!

NMatrix requires a C compiler, and has been tested only
with GCC 4.6+. We are happy to accept contributions
which improve the portability of this project.

If you are upgrading from NMatrix 0.1.0 and rely on
ATLAS features, please check the README.

Faster matrix calculations and more advanced linear
algebra features are available by installing either
the nmatrix-atlas or nmatrix-lapacke plugins.

More explicit instructions for NMatrix and SciRuby should
be available on the SciRuby website, sciruby.com, or
through our mailing list (which can be found on our web-
site).

Thanks for trying out NMatrix! Happy coding!

***********************************************************
Successfully installed nmatrix-0.2.1
1 gem installed

C:\Users\am\temp\nmatrix>git log -n 1
commit c48a3a1c5cc3eb3ab4f03dcba4cc0fc7eede5f5a
Merge: 92da6e5 b84da06
Author: Dr. John Woods <john.o.woods@gmail.com>
Date:   Mon Apr 11 14:33:43 2016 -0500

    Merge pull request #502 from preetpalS/FixForNullDeviceHavingDifferentNameOnWindows

    Workaround for Windows having a different name for null device (extconf.rb)

C:\Users\am\temp\nmatrix>irb
irb(main):001:0> require 'nmatrix'
LoadError: 126: The specified module could not be found.   - C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/nmatrix-0.2.1/lib/nmatrix.so
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/nmatrix-0.2.1/lib/nmatrix/nmatrix.rb:38:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/nmatrix-0.2.1/lib/nmatrix.rb:28:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from (irb):1
        from C:/Ruby23-x64/bin/irb.cmd:19:in `<main>'
irb(main):002:0> exit

C:\Users\am\temp\nmatrix>echo %PATH%
C:\Program Files\Haskell\bin;C:\Program Files\Haskell Platform\7.10.3\lib\extralibs\bin;C:\Program Files\Haskell Platform\7.10.3\bin;C:\Program Files\ImageMagick-6.9.3-Q16;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\CMake\bin;C:\Go\bin;C:\Program Files\nodejs\;C:\Program Files\Rust stable GNU 1.7\bin;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Haskell Platform\7.10.3\mingw\bin;C:\Program Files (x86)\scala\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Ruby23-x64\bin;C:\Users\am\AppData\Roaming\cabal\bin;C:\Users\am\Anaconda3;C:\Users\am\Anaconda3\Scripts;C:\Users\am\Anaconda3\Library\bin;C:\jruby-9.0.5.0\bin;C:\Program Files\Docker Toolbox;C:\Ruby22-x64-devkit\mingw\bin;C:\Ruby22-x64-devkit\bin;C:\Users\am\AppData\Roaming\npm

C:\Users\am\temp\nmatrix>C:\Ruby23-x64-devkit\devkitvars.bat
Adding the DevKit to PATH...

C:\Users\am\temp\nmatrix>irb
irb(main):001:0> require 'nmatrix'
=> true
irb(main):002:0> N[[1]]
=> #<NMatrix:0x0000000362af68 shape:[1,1] dtype:int32 stype:dense>
irb(main):003:0> exit

C:\Users\am\temp\nmatrix>echo %PATH%
C:\Ruby23-x64-devkit\bin;C:\Ruby23-x64-devkit\mingw\bin;C:\Program Files\Haskell\bin;C:\Program Files\Haskell Platform\7.10.3\lib\extralibs\bin;C:\Program Files\Haskell Platform\7.10.3\bin;C:\Program Files\ImageMagick-6.9.3-Q16;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\CMake\bin;C:\Go\bin;C:\Program Files\nodejs\;C:\Program Files\Rust stable GNU 1.7\bin;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Haskell Platform\7.10.3\mingw\bin;C:\Program Files (x86)\scala\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Ruby23-x64\bin;C:\Users\am\AppData\Roaming\cabal\bin;C:\Users\am\Anaconda3;C:\Users\am\Anaconda3\Scripts;C:\Users\am\Anaconda3\Library\bin;C:\jruby-9.0.5.0\bin;C:\Program Files\Docker Toolbox;C:\Ruby22-x64-devkit\mingw\bin;C:\Ruby22-x64-devkit\bin;C:\Users\am\AppData\Roaming\npm

C:\Users\am\temp\nmatrix>ls C:\Ruby23-x64-devkit\mingw\bin
aclocal          autoscan         gcc.exe              libgfortran-3.dll    strings.exe
aclocal-1.11     autoscan-2.13    gcj.exe              libgomp-1.dll        strip.exe
addr2line.exe    autoscan-2.68    gcov.exe             liblzma-1.dll        which.exe
ar.exe           autoupdate       gdb.exe              libquadmath-0.dll    windmc.exe
as.exe           autoupdate-2.13  gdbserver.exe        libssp-0.dll         windres.exe
autoconf         autoupdate-2.68  gfortran.exe         libstdc++-6.dll      x86_64-w64-mingw32-c++.exe
autoconf-2.13    bsdcpio.exe      gprof.exe            libtool              x86_64-w64-mingw32-g++.exe
autoconf-2.68    bsdtar.exe       ifnames              libtoolize           x86_64-w64-mingw32-gcc-4.7.2.exe
autoheader       c++.exe          ifnames-2.13         libwinpthread-1.dll  x86_64-w64-mingw32-gcc-ar.exe
autoheader-2.13  c++filt.exe      ifnames-2.68         libz-1.dll           x86_64-w64-mingw32-gcc-nm.exe
autoheader-2.68  cpp.exe          jcf-dump.exe         mingw32-make.exe     x86_64-w64-mingw32-gcc-ranlib.exe
autom4te         dlltool.exe      ld.bfd.exe           nm.exe               x86_64-w64-mingw32-gcc.exe
autom4te-2.68    dllwrap.exe      ld.exe               objcopy.exe          x86_64-w64-mingw32-gcj.exe
automake         elfedit.exe      lib                  objdump.exe          x86_64-w64-mingw32-gfortran.exe
automake-1.11    g++.exe          libarchive-2.dll     python27.dll
autoreconf       gcc-ar.exe       libbz2-2.dll         ranlib.exe
autoreconf-2.13  gcc-nm.exe       libexpat-1.dll       readelf.exe
autoreconf-2.68  gcc-ranlib.exe   libgcc_s_sjlj-1.dll  size.exe

C:\Users\am\temp\nmatrix>ls C:\Ruby23-x64-devkit\bin
[.exe          dirname.exe                install.exe             msys-intl-8.dll     pod2text      stat.exe
a2p.exe        dprofpp                    install.exe.manifest    msys-magic-1.dll    pod2usage     stty.exe
awk.exe        du.exe                     instmodsh               msys-perl5_8.dll    pod_cover     su.exe
basename.exe   echo.exe                   join.exe                msys-regex-1.dll    podchecker    sum.exe
bash.exe       egrep.exe                  kill.exe                msys-termcap-0.dll  podselect     sync.exe
bashbug        enc2xs                     ld2                     msys-z.dll          pr.exe        tac.exe
bison.exe      env.exe                    less.exe                msysinfo            printenv.exe  tail.exe
c2ph           error-mode.exe             lessecho.exe            msysmnt.exe         printf.exe    tee.exe
cat.exe        expand.exe                 lesskey.exe             mv.exe              prove         test.exe
chgrp.exe      expr.exe                   libnetcfg               nice.exe            ps.exe        texi2dvi
chmod.exe      factor.exe                 link.exe                nl.exe              psed          texi2pdf
chown.exe      false.exe                  ln.exe                  nohup.exe           pstruct       texindex.exe
chroot.exe     fgrep.exe                  lnkcnv                  od.exe              ptar          touch.exe
cksum.exe      file.exe                   logname.exe             oldfind.exe         ptardiff      tr.exe
cls            find.exe                   ls.exe                  paste.exe           ptee          true.exe
clsb           find2perl                  lwp-download            pathchk.exe         ptx.exe       tsort.exe
cmd            flex.exe                   lwp-mirror              pdftexi2dvi         pwd.exe       tty.exe
cmp.exe        fmt.exe                    lwp-request             perl.exe            readlink.exe  umount
comm.exe       fold.exe                   lwp-rget                perl5.8.8.exe       rm.exe        uname.exe
config_data    ftp                        m4.exe                  perlbug             rmdir.exe     unexpand.exe
cp.exe         gawk-3.1.7.exe             make.exe                perlcc              s2p           uniq.exe
cpan           gawk.exe                   makeinfo.exe            perldoc             scandeps.pl   unlink.exe
cpantest       grep.exe                   md5sum.exe              perlivp             sdiff.exe     users.exe
crc32          groups                     mintty.exe              perlld              sed.exe       vdir.exe
crypt.exe      h2ph                       mkdir.exe               perlrebase          seq.exe       wc.exe
csplit.exe     h2xs                       mkfifo.exe              pgawk-3.1.7.exe     sh.exe        which
cut.exe        head.exe                   mknod.exe               pgawk.exe           sha1sum.exe   who.exe
date.exe       hostname.exe               mksh.exe                piconv              shasum        whoami.exe
dd.exe         id.exe                     mount                   pinky.exe           shred.exe     xargs.exe
df.exe         igawk                      msys-1.0.dll            pl2pm               sleep.exe     xsubpp
diff.exe       info.exe                   msys-crypt-0.dll        pod2html            sort.exe      yacc
diff3.exe      infokey.exe                msys-gdbm-3.dll         pod2latex           splain        yes.exe
dir.exe        install-info.exe           msys-gdbm_compat-3.dll  pod2man             split.exe     ysh
dircolors.exe  install-info.exe.manifest  msys-iconv-2.dll        pod2readme          start

C:\Users\am\temp\nmatrix>`

**Comment by thrabbit** [comment]
Adding my devkit vars to my path prior to running Rails did fix the issue. Thanks a lot for helping in fixing this issue, maybe it will help other users.

**Comment by preetpalS** [comment]
@thrabbit I am glad to hear that I could help you. =)

**Comment by mohawkjohn** [comment]
Thanks so much for answering this question! And for the detailed information. I'm sure it'll prove helpful for others in the future. =)
