### ISSUE TITLE
Use 'true' and 'false' like narray

### ISSUE THREAD

**Issue by edmundhighcock** [SciRuby/nmatrix#512]
One of the features I really liked about NArray was the ability to use 'true' within [] to indicate the whole of a dimension, and 'false' to expand to as many 'true's as necessary:

I quote from the narray documentation

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
a[ 0, true ]	sams as a[0,0..-1]. `true' means all.
    a[ false, 0 ]	same as a[true,true,0], if a is a 3-d array,
			`false' means ellipsis dimension.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This feature was very useful as it frequently avoided boilerplate. Is there a reason (e.g. performance) why it was not adopted by nmatrix? I'd be happy to have a go at forking and adding this feature if no-one objects.

**Comment by mohawkjohn** [comment]
@edmundhighcock Try `:*` instead of `true`. =)

**Comment by edmundhighcock** [comment]
Great, thanks!

And false? I know I'm being really lazy now!

**Comment by edmundhighcock** [comment]
I guess 

~~~~~~~~~~~~~~~~~~
a[ *[:*]*a.dim - 1, 4]
~~~~~~~~~~~~~~~~~~~~~

is equivalent to

~~~~~~~~~~~~~~~~~~~~~
a[false, 4]
~~~~~~~~~~~~~~~~~~

although a little more cryptic!

**Comment by edmundhighcock** [comment]
Last question, and not strictly related to the title so apologies. With narray, you can do this

b = a[ [0,2,3], true]

which would create a new narray of shape (3, x) where x is the size of the second dim of a. In effect you're doing something like Array#values_at. Is there an NMatrix equivalent?

**Comment by mohawkjohn** [comment]
I don't believe so. We have a feature that creates references (which are not copies) of contiguous portions, but it doesn't do non-contiguous portions. It'd be easy to implement a copy operation for that, but a reference operation would be much harder. The challenge is in the other storage types (yale and list matrices).

There's no shorthand option equivalent to `false` because no one's needed it so far. However, it is possible to take an arbitrary slice of a 3D matrix using a different method: `NMatrix#rank`. Give that a try and see if it does what you want.

**Comment by mohawkjohn** [comment]
@edmundhighcock I'm going to close this, but feel free to re-open if you are interested in working on implementing this as an extra feature — or if you have questions. =)

**Comment by edmundhighcock** [comment]
No problems. I have what I need for now; I think a copy operation for the non-contiguous portions would be useful, so when I have time I'll get back to it (which may be a while =) )
