### ISSUE TITLE
Adding a Least Squares Solver

### ISSUE THREAD

**Issue by gau27** [SciRuby/nmatrix#513]
The Least Squares Solution function is something that was intended to follow the addition of QR factorization,  these were the manual steps to get the least squares solution from using the QR factorization routines mentioned by @wlevine on the discussion thread of this [pull request](https://github.com/SciRuby/nmatrix/pull/490)

> use geqrf to get Q and R, then ormqr to get (Q_1^T b), and then trsm to solve R_1 x = Q_1^T b

However, LAPACK offers [4 methods](http://www.netlib.org/lapack/lug/node27.html) to solve the general least squares problem.

>  xGELSX and xGELSY use a complete orthogonal factorization of A, while xGELSS uses the singular value decomposition of A, and xGELSD uses the singular value decomposition of A with an algorithm based on divide and conquer. 

I believe the latter would be faster due to the absence of intermediate ruby objects to store the factorizations but I'm not sure if adding it is warranted when we could use a few lines of ruby code and use the existing solver function to get the correct result.

@agisga : How do you think we should proceed? Should we consider including all the solver functions from LAPACK ? Is there any advantage use case for using QR factorization versus SVD?

**Comment by agisga** [comment]
@gau27 QR factorization is actually faster than SVD for least squares, but it fails when the matrix is not full rank and accumulates more error than SVD (see for example [this overview](http://www.cs.princeton.edu/courses/archive/fall11/cos323/notes/cos323_f11_lecture09_svd.pdf)). As far as I know, QR is regarded as the standard for least squares problems.

From the link you provided, xGELS which uses a QR or LQ factorization, seems to be the standard LAPACK function for least squares. The four methods from the quote that you give, can handle rank deficiencies, but are, I think, slower than xGELS.

Should we consider including solver functions from LAPACK? Sure, if you have the time :P. Otherwise, I think that a Ruby implementation is better than nothing, would not involve much work at this point, and can be replaced at a later point in time.

**Comment by gau27** [comment]
All right, I'll begin work on the Ruby patch for this until the LAPACKE functions are exposed. What should be the behavior for an under-determined system? Is the error negligible enough to issue a warning or should we just reject rank-deficient matrices?

**Comment by mohawkjohn** [comment]
I'm looking at some of my least squares code for a separate project (sorry, can't share, flight software) and it looks like I do the following:

* Attempt a Cholesky decomposition.
 * Error if any diagonal element is negative.
 * Error if the square root of any diagonal element is 0.
 * Warning if the square root of any diagonal element is non-zero but very close to 0.
* If Cholesky fails, attempt an LDL' decomposition. (This should not need to be done, since least squares decompositions are only supposed to be performed, but I needed the code to be especially fault tolerant. If LDL occurs, a warning is issued.)
 * Error if the denominator in the division is 0.
 * Warning if the denominator in the division is close to 0.

I don't know if any of this actually answers your question. Here's the take-away:

If you're going to divide by 0 or take the square root of a negative number, you need to give an error. If the results are not likely to be reliable (you're dividing by something very small), you need to give a warning.

**Comment by agisga** [comment]
@gau27 I agree with John. If you use QR factorization, you can issue a warning when any diagonal element of R is close to zero (error when equal to zero).
I think that checking matrix rank would add too much of a computational overhead, without much reward, because rank deficient matrices are rare in practice (in my understanding).
