### ISSUE TITLE
Initialize a matrix from columns

### ISSUE THREAD

**Issue by lokeshh** [SciRuby/nmatrix#536]
Is there a method to initialize matrix from columns?

Currently I use the following for this task.

``` ruby
> n = N[[1, 2], [3, 4]].transpose
=> 
[
  [1, 3]   [2, 4] ]
```

**Comment by v0dro** [comment]
I don't think there is. @mohawkjohn would that be possible given the row-major representation of numbers that nmatrix uses internally?

**Comment by lokeshh** [comment]
@v0dro I just want something similar to [Matrix#columns](http://ruby-doc.org/stdlib-2.3.0/libdoc/matrix/rdoc/Matrix.html#method-c-columns). The representation doesn't matter.

**Comment by mohawkjohn** [comment]
I'd probably do something like

```
n = NMatrix.new([2,2], dtype: :float64)
n[:*,0] = column0
n[:*,1] = column1
```

That's going to be the most efficient. You could easily add an `NMatrix.columns` method that does this exact thing.

Note that if you *do* attempt such a thing, the most efficient solution for `:object` will be slightly different, since `:object` matrices have to get allocated *and* initialized when you call `new` (all other matrices are allocated and *not* initialized).

**Comment by mohawkjohn** [comment]
It might also be efficient to initialize the columns as rows and then just transpose. I'm going to go ahead and close this.
