### ISSUE TITLE
Is Ruby 1.9.3 supported?

### ISSUE THREAD

**Issue by lokeshh** [SciRuby/nmatrix#599]
The README says 1.9.3 is supported but `.travis.yml` doesn't include it.

**Comment by mohawkjohn** [comment]
Looks like we removed support for 1.9.3 in #552 because it had reached end-of-life:

https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

It's also possible Travis no longer supports 1.9.3. The commit message is a little vague.

Do you want to give it a shot and let me know if you're able to build? Thanks for catching this.

**Comment by lokeshh** [comment]
> Do you want to give it a shot and let me know if you're able to build? Thanks for catching this.

I tried and the build failed in 1.9.3

**Comment by v0dro** [comment]
We don't need to support 1.9.3
